### PR TITLE
`Lexer`'s __init__ now only takes template_string as arg

### PR DESCRIPTION
**Pull request by sarina**
See the Django source as of tag 1.9.1a: https://github.com/django/django/blob/f20364c7d0be555afe7bebd5d15154b59e8cba2e/django/template/base.py#L361

### CODE REVIEW

**Comment by sarina** [comment]
Specifically, the commit that changes the definition is here: https://github.com/django/django/commit/55f12f8709f0604df7e1817a4c114ead1fb9a311 and is first present in 1.9.1 tags.

**Comment by sarina** [comment]
Right now we can't fully fix the build, because this same error exists in an underlying library:

```
.tox/2.7-master/lib/python2.7/site-packages/django_babel/extract.py:35: in extract_django
    for t in Lexer(text, None).tokenize():
E   TypeError: __init__() takes exactly 2 arguments (3 given)
```

**Comment by sarina** [comment]
Fixed the base library: https://github.com/python-babel/django-babel/pull/21

**Comment by EnTeQuAk** [comment]
Thanks a lot for the pull request! I now have django 1.9 support in master and will release a new version once Travis is green.

**Pull request closed without merging**
